name: Release And Publish Package
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v2
      - name: Get Latest Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create Release 
        uses: ntltd/release-generator@master
        with:
          baseTag: ${{ steps.bump_version.outputs.previous_tag }}
          releaseTag: ${{ env.RELEASE_VERSION }}
          prerelease: false
          draft: false
          releaseName: ${{ env.RELEASE_VERSION }}
          templatePath: templates/release.md
          token: ${{ github.token }}