name: Build And Deploy StoryBook
on: 
  push:
    paths: ["src/**", ".storybook/**"] 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: |
          npm install
          npm run build-storybook
      - name: Deploy 🚀
        run: |
          npm run deploy